language: node_js
node_js: "5.5.0"
sudo: false
script:
  - npm run test-single
after_success:
  - travis_retry npm install codecov.io
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
